### ISSUE TITLE
Requirements for building the documentation are not up to date

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#2429]
One of the requirements listed for the tools needed to build the ACRN documentation is `kconfiglib==10.*`. This isn't quite accurate as any version below 10.2 will fail in some fashion (see examples below).

With `kconfiglib==10.1.1`:
-----------------------------------
```
make -C /home/gvancuts/work/acrn/acrn-hypervisor/doc html BUILDDIR=/home/gvancuts/work/acrn/acrn-hypervisor/build/doc
make[1]: Entering directory '/home/gvancuts/work/acrn/acrn-hypervisor/doc'
Traceback (most recent call last):
  File "scripts/genrest.py", line 441, in <module>
    write_kconfig_rst()
  File "scripts/genrest.py", line 96, in write_kconfig_rst
    write_sym_rst(sym, out_dir)
  File "scripts/genrest.py", line 123, in write_sym_rst
    kconfig_definition_rst(sym))
  File "scripts/genrest.py", line 376, in kconfig_definition_rst
    include_path(node), menu_path(node),
  File "scripts/genrest.py", line 335, in include_path
    if not node.include_path:
AttributeError: 'MenuNode' object has no attribute 'include_path'
make[1]: *** [Makefile:48: kconfig] Error 1
make[1]: Leaving directory '/home/gvancuts/work/acrn/acrn-hypervisor/doc'
make: *** [Makefile:72: doc] Error 2
```

With `kconfiglib==10.0.0`:
----------------------------------
```
make -C /home/gvancuts/work/acrn/acrn-hypervisor/doc html BUILDDIR=/home/gvancuts/work/acrn/acrn-hypervisor/build/doc
make[1]: Entering directory '/home/gvancuts/work/acrn/acrn-hypervisor/doc'
Traceback (most recent call last):
  File "scripts/genrest.py", line 441, in <module>
    write_kconfig_rst()
  File "scripts/genrest.py", line 94, in write_kconfig_rst
    for sym in sorted(kconf.unique_defined_syms, key=lambda sym: sym.name):
AttributeError: 'Kconfig' object has no attribute 'unique_defined_syms'
make[1]: *** [Makefile:48: kconfig] Error 1
make[1]: Leaving directory '/home/gvancuts/work/acrn/acrn-hypervisor/doc'
make: *** [Makefile:72: doc] Error 2
```

**Comment by gvancuts** [comment]
The fix (#2430) was merged, closing this issue.
