### ISSUE TITLE
Errors when building the documentation (`make html` on Fedora 27)

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#395]
I followed [these instructions](https://projectacrn.github.io/latest/howtos/process/docbuild.html#installing-the-documentation-tools) to install the dependencies to build the documentation but I am encountering the following error(s) when running `make html`. I am on Fedora 27.

```
$ make html
make: [Makefile:42: html] Error 1 (ignored)

New errors/warnings found, please fix them:
==============================================

warning: Tag `CLANG_ASSISTED_PARSING' at line 1048 of file `-' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
warning: Tag `CLANG_OPTIONS' at line 1056 of file `-' belongs to an option that was not enabled at compile time.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u", or recompile doxygen with this feature enabled.
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 7, in <module>
    from sphinx.cmd.build import main
ModuleNotFoundError: No module named 'sphinx.cmd'
```

**Comment by gvancuts** [comment]
The following patch gets me passed the initial warning (although I don't believe the warning is fatal):
```
diff --git a/doc/acrn.doxyfile b/doc/acrn.doxyfile
index 96b54ea..2c44681 100644
--- a/doc/acrn.doxyfile
+++ b/doc/acrn.doxyfile
@@ -1045,7 +1045,7 @@ VERBATIM_HEADERS       = YES
 # generated with the -Duse-libclang=ON option for CMake.
 # The default value is: NO.
 
-CLANG_ASSISTED_PARSING = NO
+#CLANG_ASSISTED_PARSING = NO
 
 # If clang assisted parsing is enabled you can provide the compiler with command
 # line options that you would normally use when invoking the compiler. Note that
@@ -1053,7 +1053,7 @@ CLANG_ASSISTED_PARSING = NO
 # specified with INPUT and INCLUDE_PATH.
 # This tag requires that the tag CLANG_ASSISTED_PARSING is set to YES.
 
-CLANG_OPTIONS          =
+#CLANG_OPTIONS          =
 
 #---------------------------------------------------------------------------
 # Configuration options related to the alphabetical class index
```

But I'm still left with this:
```
$ make html
make: [Makefile:42: html] Error 1 (ignored)

New errors/warnings found, please fix them:
==============================================

Traceback (most recent call last):
  File "/usr/local/bin/sphinx-build", line 7, in <module>
    from sphinx.cmd.build import main
ModuleNotFoundError: No module named 'sphinx.cmd'
```

The `sphinx-build` package is broken but I'm not sure how to fix this.

@dbkinder , is the patch that got me passed the first part of the error suitable for inclusion or do we just live with the warning?

**Comment by gvancuts** [comment]
As an experiment, I removed all versions specified in `doc/script/requirements` and re-installed all dependencies. I'm now able to successfully generate the HTML documentation on my Fedora 27 systems. Here are the versions installed on my system:
```
Name: breathe
Version: 4.9.1
Summary: Sphinx Doxygen renderer
Home-page: https://github.com/michaeljones/breathe
Author: Michael Jones
Author-email: m.pricejones@gmail.com
License: BSD
Location: /home/gvancuts/.local/lib/python3.6/site-packages
Requires: docutils, six, Sphinx
---
Name: Sphinx
Version: 1.7.5
Summary: Python documentation generator
Home-page: http://sphinx-doc.org/
Author: Georg Brandl
Author-email: georg@python.org
License: BSD
Location: /home/gvancuts/.local/lib/python3.6/site-packages
Requires: Pygments, Jinja2, requests, babel, six, alabaster, docutils, imagesize, sphinxcontrib-websupport, snowballstemmer, packaging, setuptools
---
Name: docutils
Version: 0.14
Summary: Docutils -- Python Documentation Utilities
Home-page: http://docutils.sourceforge.net/
Author: docutils-develop list
Author-email: docutils-develop@lists.sourceforge.net
License: public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
Location: /home/gvancuts/.local/lib/python3.6/site-packages
Requires: 
---
Name: sphinx-rtd-theme
Version: 0.4.0
Summary: Read the Docs theme for Sphinx
Home-page: https://github.com/rtfd/sphinx_rtd_theme/
Author: Dave Snider, Read the Docs, Inc. & contributors
Author-email: dev@readthedocs.org
License: MIT
Location: /home/gvancuts/.local/lib/python3.6/site-packages
Requires: 
```
