### ISSUE TITLE
[TGL][acrn-configuration-tool] generate tgl launch script fail

### ISSUE THREAD

**Issue by liuwei987** [projectacrn/acrn-hypervisor#5091]
++ board=tgl-rvp
++ export board_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/board-xmls/tgl-rvp.xml
++ board_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/board-xmls/tgl-rvp.xml
++ export scenario_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml
++ scenario_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml
++ export launch_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml
++ launch_file=/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml
++ python /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/launch_cfg_gen.py --board /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/board-xmls/tgl-rvp.xml --scenario /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml --launch /root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml --uosid 0
Traceback (most recent call last):
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/launch_cfg_gen.py", line 240, in <module>
    err_dic = main(ARGS)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/launch_cfg_gen.py", line 225, in main
    err_dic = generate_script_file(names, pt_sel, virt_io.dev, dm.args, post_vm_i, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/launch_cfg_gen.py", line 138, in generate_script_file
    com.gen(names, pt_sel, virt_io, dm, vmid, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/com.py", line 634, in gen
    launch_begin(names, virt_io, vmid, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/com.py", line 282, in launch_begin
    tap_network(virt_io, vmid, config)
  File "/root/RUI/workspace/weekly/cwpqa-acrn-robot/acrn-hypervisor/misc/acrn-config/launch_config/com.py", line 248, in tap_network
    tap_net_list = virt_io['network'][vmid]
KeyError: 1

**Comment by liuwei987** [comment]
[External_System_ID] ACRN-6571
