### ISSUE TITLE
Runtime dependencies for the ACRN configuration tool not documented

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#5646]
You need to have `flask` and `flask_bootstrap` installed on your development system in order to run the ACRN configuration tool. These dependencies are not documented in our online documents.

You will get the following error if you do not have `flask_bootstrap` installed:
```
$ python3 misc/acrn-config/config_app/app.py 
Traceback (most recent call last):
  File "misc/acrn-config/config_app/app.py", line 16, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```

You will get the following error if you do not have `flask_bootstrap` installed:
```
$ python3 misc/acrn-config/config_app/app.py 
Traceback (most recent call last):
  File "misc/acrn-config/config_app/app.py", line 21, in <module>
    from flask_bootstrap import Bootstrap
ModuleNotFoundError: No module named 'flask_bootstrap'
```

On Ubuntu, you can install these tools as follows:
```
$ sudo apt install python3-flask
$ pip3 install --user flask_bootstrap
```

**Comment by gvancuts** [comment]
My bad, it is in fact documented here: https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html?highlight=requirements#prerequisites ... closing this :-)
