### ISSUE TITLE
virtio: NULL deref in hw/pci/virtio/virtio.c:664 in vq_endchains

### ISSUE THREAD

**Issue by yonghuah** [projectacrn/acrn-hypervisor#6129]
NULL deref + SEGV when fuzzing with Hypercube guest VM

HV version 2.5-unstable-2021-05-02 00:15:42-83a2f0924 DBG (daily tag:acrn-2021w18.5-180000p) sdc@qemu build

*__________________________*

After applying the fix for ACRN-7101, we encounter another NULL deref that seems to be in underlying virtio ringbuffer:

{noformat}
hw/pci/virtio/virtio.c:664:26: runtime error: member access within null pointer of type 'volatile struct vring_used'AddressSanitizer:DEADLYSIGNAL
=================================================================
==1175==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000002 (pc 0x56338eaed5f7 bp 0x7ffe59aa4460 sp 0x7ffe59aa4420 T0)
==1175==The signal is caused by a READ memory access.
==1175==Hint: address points to the zero page.
Round 0000000k: s = { .a=29d2bf4f, .b=076e78b3, .c=031978ce, .d=7a98e067 };
#0 0x56338eaed5f6 in vq_endchains hw/pci/virtio/virtio.c:664
#1 0x56338ec2ed46 in virtio_net_tap_rx hw/pci/virtio/virtio_net.c:413
#2 0x56338ec2e3d9 in virtio_net_rx_callback hw/pci/virtio/virtio_net.c:477
#3 0x56338ec9f8d2 in mevent_handle core/mevent.c:203
#4 0x56338eca2b65 in mevent_dispatch core/mevent.c:441
#5 0x56338ecc0873 in main core/main.c:1091
#6 0x7f0b5be2809a in __libc_start_main ../csu/libc-start.c:308
#7 0x56338e996dfd in _start (/home/pepe/acrn-dm.fix_rb+resetv2+net+0x1eadfd)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV hw/pci/virtio/virtio.c:664 in vq_endchains
==1175==ABORTING
{noformat}

**Comment by yonghuah** [comment]
[External_System_ID] ACRN-7168
