### ISSUE TITLE
member access within null pointer of type 'struct xhci_trb'

### ISSUE THREAD

**Issue by Ragnarliu** [projectacrn/acrn-hypervisor#6172]
**Describe the bug**

hw/pci/xhci.c:2634:10: runtime error: member access within null pointer of type 'struct xhci_trb'
                                                                                                 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==474==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000000c (pc 0x55d7ce7b0cec bp 0x7f09a07f9990 sp 0x7f09a07f9880 T15)
==474==The signal is caused by a READ memory access.
==474==Hint: address points to the zero page.
#0 0x55d7ce7b0ceb in pci_xhci_complete_commands hw/pci/xhci.c:2634
#1 0x55d7ce7b2979 in pci_xhci_dbregs_write hw/pci/xhci.c:3396
#2 0x55d7ce7b2f0c in pci_xhci_write hw/pci/xhci.c:3634
#3 0x55d7ce7b9fa8 in pci_emul_mem_handler hw/pci/core.c:532                      
#4 0x55d7ce8ac134 in mem_write core/mem.c:148
#5 0x55d7ce8b5999 in emulate_mem core/mem.c:187 
#6 0x55d7ce8c22c3 in vmexit_mmio_emul core/main.c:334             
#7 0x55d7ce8c134e in handle_vmexit core/main.c:405                                                                         
#8 0x55d7ce8c198f in vm_loop core/main.c:702
#9 0x55d7ce8c2b56 in start_thread core/main.c:249 
#10 0x7f0aec0bffa2 in start_thread /build/glibc-vjB4T1/glibc-2.28/nptl/pthread_create.c:486
#11 0x7f0aeac154ce in clone (/lib/x86_64-linux-gnu/libc.so.6+0xf94ce)AddressSanitizer can not provide additional info.                                     
SUMMARY: AddressSanitizer: SEGV hw/pci/xhci.c:2634 in pci_xhci_complete_commands      
Thread T15 (vcpu 0) created by T0 (mevent) here:
#0 0x55d7ce5b2ab5 in pthread_create (/home/pepe/acrn-dm.fix_rb+resetv2+net+0x202ab5)     
#1 0x55d7ce8bfcd4 in add_cpu core/main.c:275
#2 0x55d7ce8c4851 in main core/main.c:1079     
#3 0x7f0aeab4009a in __libc_start_main ../csu/libc-start.c:308                               
==474==ABORTING

**Comment by Ragnarliu** [comment]
[External_System_ID] ACRN-7158
