### ISSUE TITLE
mem leak while poweroff in guest

### ISSUE THREAD

**Issue by liudlong** [projectacrn/acrn-hypervisor#6533]
Test target:  mainline (commit id: c4cb95f3b4023a58b6ceeaa59b8677a2c5c54c24) + 2 hypercube patches with unchanged 2.5 kernel
Test tool: 5 latest Hypercube iso:  hypercube_APIC.iso/ hypercube_PCI_HPET.iso/ hypercube_PCI_USB.iso/ hypercube_PCI_ecam.iso/ hypercube_PIO.iso, built with new scrip- build-all.sh.
Test method: 1: try industry scenario on TGL. 2: only boot 1 guest with 1 vcpu. 3: use same launch parameters temporarily
poweroff normal guest, not need fuzzing

 __________________________

 

==357==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32816 byte(s) in 1 object(s) allocated from:
#0 0x55997c92a000 in __interceptor_malloc (/usr/bin/acrn-dm+0x230000)
#1 0x7f9fc7bfd906 (/lib/libc.so.6+0xc3906)

Direct leak of 152 byte(s) in 1 object(s) allocated from:
#0 0x55997c92a1e8 in __interceptor_calloc (/usr/bin/acrn-dm+0x2301e8)
#1 0x7f9fc8b7fcc5 (/lib/libusb-1.0.so.0+0x4cc5)

Indirect leak of 2048 byte(s) in 2 object(s) allocated from:
#0 0x55997c92a3f0 in __interceptor_realloc (/usr/bin/acrn-dm+0x2303f0)
#1 0x7f9fc8b8a79e (/lib/libusb-1.0.so.0+0xf79e)

Indirect leak of 416 byte(s) in 2 object(s) allocated from:
#0 0x55997c92a1e8 in __interceptor_calloc (/usr/bin/acrn-dm+0x2301e8)
#1 0x7f9fc8b8430f in libusb_alloc_transfer (/lib/libusb-1.0.so.0+0x930f)
#2 0x55997c9a43a2 in usb_dev_data hw/platform/usb_pmapper.c:810
#3 0x55997ca2643f in pci_xhci_try_usb_xfer hw/pci/xhci.c:3002
#4 0x55997ca2c4a1 in pci_xhci_handle_transfer hw/pci/xhci.c:3271
#5 0x55997ca2f562 in pci_xhci_device_doorbell hw/pci/xhci.c:3380
#6 0x55997ca324ca in pci_xhci_dbregs_write hw/pci/xhci.c:3403
#7 0x55997ca32916 in pci_xhci_write hw/pci/xhci.c:3639
#8 0x55997ca3950a in pci_emul_mem_handler hw/pci/core.c:532
#9 0x55997caffebb in mem_write core/mem.c:148
#10 0x55997cb07212 in emulate_mem core/mem.c:187
#11 0x55997cb12156 in vmexit_mmio_emul core/main.c:336
#12 0x55997cb115b8 in handle_vmexit core/main.c:407
#13 0x55997cb11a22 in vm_loop core/main.c:707
#14 0x55997cb12812 in start_thread core/main.c:251
#15 0x7f9fc8e72ea3 (/lib/libpthread.so.0+0x8ea3)

Indirect leak of 152 byte(s) in 1 object(s) allocated from:
#0 0x55997c92a1e8 in __interceptor_calloc (/usr/bin/acrn-dm+0x2301e8)
#1 0x7f9fc8b7fcc5 (/lib/libusb-1.0.so.0+0x4cc5)

Indirect leak of 128 byte(s) in 2 object(s) allocated from:
#0 0x55997c92a1e8 in __interceptor_calloc (/usr/bin/acrn-dm+0x2301e8)
#1 0x55997c99d631 in usb_dev_alloc_req hw/platform/usb_pmapper.c:339
#2 0x55997c9a43a2 in usb_dev_data hw/platform/usb_pmapper.c:810
#3 0x55997ca2643f in pci_xhci_try_usb_xfer hw/pci/xhci.c:3002
#4 0x55997ca2c4a1 in pci_xhci_handle_transfer hw/pci/xhci.c:3271
#5 0x55997ca2f562 in pci_xhci_device_doorbell hw/pci/xhci.c:3380
#6 0x55997ca324ca in pci_xhci_dbregs_write hw/pci/xhci.c:3403
#7 0x55997ca32916 in pci_xhci_write hw/pci/xhci.c:3639
#8 0x55997ca3950a in pci_emul_mem_handler hw/pci/core.c:532
#9 0x55997caffebb in mem_write core/mem.c:148
#10 0x55997cb07212 in emulate_mem core/mem.c:187
#11 0x55997cb12156 in vmexit_mmio_emul core/main.c:336
#12 0x55997cb115b8 in handle_vmexit core/main.c:407
#13 0x55997cb11a22 in vm_loop core/main.c:707
#14 0x55997cb12812 in start_thread core/main.c:251
#15 0x7f9fc8e72ea3 (/lib/libpthread.so.0+0x8ea3)

Indirect leak of 112 byte(s) in 2 object(s) allocated from:
#0 0x55997c92a1e8 in __interceptor_calloc (/usr/bin/acrn-dm+0x2301e8)
#1 0x7f9fc8b87679 (/lib/libusb-1.0.so.0+0xc679)

Indirect leak of 11 byte(s) in 2 object(s) allocated from:
#0 0x55997c92a000 in __interceptor_malloc (/usr/bin/acrn-dm+0x230000)
#1 0x55997c99da01 in usb_dev_alloc_req hw/platform/usb_pmapper.c:352
#2 0x55997c9a43a2 in usb_dev_data hw/platform/usb_pmapper.c:810
#3 0x55997ca2643f in pci_xhci_try_usb_xfer hw/pci/xhci.c:3002
#4 0x55997ca2c4a1 in pci_xhci_handle_transfer hw/pci/xhci.c:3271
#5 0x55997ca2f562 in pci_xhci_device_doorbell hw/pci/xhci.c:3380
#6 0x55997ca324ca in pci_xhci_dbregs_write hw/pci/xhci.c:3403
#7 0x55997ca32916 in pci_xhci_write hw/pci/xhci.c:3639
#8 0x55997ca3950a in pci_emul_mem_handler hw/pci/core.c:532
#9 0x55997caffebb in mem_write core/mem.c:148
#10 0x55997cb07212 in emulate_mem core/mem.c:187
#11 0x55997cb12156 in vmexit_mmio_emul core/main.c:336
#12 0x55997cb115b8 in handle_vmexit core/main.c:407
#13 0x55997cb11a22 in vm_loop core/main.c:707
#14 0x55997cb12812 in start_thread core/main.c:251
#15 0x7f9fc8e72ea3 (/lib/libpthread.so.0+0x8ea3)

Indirect leak of 9 byte(s) in 2 object(s) allocated from:
#0 0x55997c8c2a18 in __interceptor_strdup (/usr/bin/acrn-dm+0x1c8a18)
#1 0x7f9fc8b8a6da (/lib/libusb-1.0.so.0+0xf6da)

SUMMARY: AddressSanitizer: 35844 byte(s) leaked in 15 allocation(s).

**Comment by liudlong** [comment]
[External_System_ID] ACRN-7292
