### ISSUE TITLE
failed to make hvdiffconfig

### ISSUE THREAD

**Issue by szhen11** [projectacrn/acrn-hypervisor#6592]
Environment
ubuntu

HW/Board
ehl-crb-b, tgl-rvp, adl-s-crb

Build link
NA

Image info
NA

Steps
1. clone acrn-hypervisor, checkout to release_2.6 branch(commit: 9bf80f916e1bdf86417de5e395dd3a4f7f62ebe7)
git am offline patches from https://github.com/intel-innersource/virtualization.hypervisors.acrn.acrn-dev.acrn-offline-patch/tree/master/boards/v2.6
2. following doc: https://projectacrn.github.io/latest/tutorials/acrn_configuration_tool.html#makefile-targets-for-configuration
to generate diff configs and apply it.

Expected result
generate diff configs and apply it successfully.

Actual result
generate diff config patch failed

Reproduce rate
100%

Debugging info

shuang@shuang-desktop:~/dev/acrn/acrn-hypervisor$ make clean
make -C /home/shuang/dev/acrn/acrn-hypervisor/misc OUT_DIR=/home/shuang/dev/acrn/acrn-hypervisor/build/misc clean
make[1]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc'
make -C /home/shuang/dev/acrn/acrn-hypervisor/misc/services/acrn_manager OUT_DIR=/home/shuang/dev/acrn/acrn-hypervisor/build/misc/services clean
make[2]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/services/acrn_manager'
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/acrnctl
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/acrn_mngr.o
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/libacrn-mngr.a
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/acrnd
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/acrn_mngr.h
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/acrnd.service
rm -rf /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services
make[2]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/services/acrn_manager'
make -C /home/shuang/dev/acrn/acrn-hypervisor/misc/services/life_mngr OUT_DIR=/home/shuang/dev/acrn/acrn-hypervisor/build/misc/services clean
make[2]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/services/life_mngr'
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/life_mngr
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services/life_mngr.service
rm -rf /home/shuang/dev/acrn/acrn-hypervisor/build/misc/services
make[2]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/services/life_mngr'
make -C /home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog OUT_DIR=/home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools clean
make[2]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog'
make -C common clean
make[3]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog/common'
Clean objects and binaries
make[3]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog/common'
make -C acrnprobe clean
make[3]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog/acrnprobe'
Clean objects and binaries
make[3]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog/acrnprobe'
make -C usercrash clean
make[3]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog/usercrash'
Clean objects and binaries
make[3]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog/usercrash'
make[2]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_crashlog'
make -C /home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_trace OUT_DIR=/home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools clean
make[2]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_trace'
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools/acrntrace
rm -rf /home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools
make[2]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_trace'
make -C /home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_log OUT_DIR=/home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools clean
make[2]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_log'
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools/acrnlog
rm -f /home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools/acrnlog.service
rm -rf /home/shuang/dev/acrn/acrn-hypervisor/build/misc/debug_tools
make[2]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc/debug_tools/acrn_log'
rm -rf /home/shuang/dev/acrn/acrn-hypervisor/build/misc
make[1]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/misc'
make -C /home/shuang/dev/acrn/acrn-hypervisor/doc BUILDDIR=/home/shuang/dev/acrn/acrn-hypervisor/build/doc clean
make[1]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/doc'
rm -fr /home/shuang/dev/acrn/acrn-hypervisor/build/doc
make[1]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/doc'
rm -rf /home/shuang/dev/acrn/acrn-hypervisor/build
shuang@shuang-desktop:~/dev/acrn/acrn-hypervisor$ make BOARD=ehl-crb-b SCENARIO=hybrid_rt hvdefconfig
make[1]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/hypervisor'
Board XML is fetched from /home/shuang/dev/acrn/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
Scneario XML is configuration fetched from /home/shuang/dev/acrn/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
/home/shuang/dev/acrn/acrn-hypervisor/build/hypervisor/configs/allocation.xml generated
/home/shuang/dev/acrn/acrn-hypervisor/build/hypervisor/configs/unified.xml generated
/home/shuang/dev/acrn/acrn-hypervisor/build/hypervisor/configs/config.mk generated
Board configurations for ehl-crb-b is generated successfully.
start to generate ACPI ASL code for VM0
generate ASL code of ACPI tables for VM 0 into /home/shuang/dev/acrn/acrn-hypervisor/build/hypervisor/configs/scenarios/hybrid_rt/ACPI_VM0
Scenario configuration files were created successfully.
/usr/bin/xsltproc
Generating vm_configurations.c:
vm_configurations.c was generated using xsltproc successfully.
Generating vm_configurations.h:
vm_configurations.h was generated using xsltproc successfully.
Generating pt_intx.c:
pt_intx.c was generated using xsltproc successfully.
Generating ivshmem_cfg.h:
ivshmem_cfg.h was generated using xsltproc successfully.
Generating misc_cfg.h:
misc_cfg.h was generated using xsltproc successfully.
Generating pci_dev.c:
pci_dev.c was generated using xsltproc successfully.
Generating board_info.h:
board_info.h was generated using xsltproc successfully.
/usr/bin/clang-format
make[1]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/hypervisor'
shuang@shuang-desktop:~/dev/acrn/acrn-hypervisor$ make hvdiffconfig
make[1]: Entering directory '/home/shuang/dev/acrn/acrn-hypervisor/hypervisor'
Board configurations for ehl-crb-b is generated successfully.
Traceback (most recent call last):
File "/home/shuang/dev/acrn/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/scenario_cfg_gen.py", line 312, in <module>
err_dic = main(ARGS)
File "/home/shuang/dev/acrn/acrn-hypervisor/hypervisor/../misc/config_tools/scenario_config/scenario_cfg_gen.py", line 286, in main
err_dic = asl_gen.main(args)
File "/home/shuang/dev/acrn/acrn-hypervisor/misc/config_tools/scenario_config/../acpi_gen/asl_gen.py", line 651, in main
allocation_etree = lxml.etree.parse(os.path.join(os.path.dirname(board), "configs", "allocation.xml"))
File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/home/shuang/dev/acrn/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/configs/allocation.xml': failed to load external entity "/home/shuang/dev/acrn/acrn-hypervisor/misc/config_tools/data/ehl-crb-b/configs/allocation.xml"
Diff on generated configuration files is available at /home/shuang/dev/acrn/acrn-hypervisor/build/hypervisor/config.patch.
To make a patch effective, use 'applydiffconfig PATCH=/path/to/patch' to register it to a build.
make[1]: Leaving directory '/home/shuang/dev/acrn/acrn-hypervisor/hypervisor'

**Comment by szhen11** [comment]
[External_System_ID] ACRN-7404
