### ISSUE TITLE
Board Inspector tool crashes if `cpuid` is not installed

### ISSUE THREAD

**Issue by gvancuts** [projectacrn/acrn-hypervisor#6719]
The Board Inspector tool will crash if `cpuid` is missing on the host system.

```
$ sudo python3 board_inspector.py ma
[sudo] password for gvancuts: 
Traceback (most recent call last):
  File "board_inspector.py", line 84, in <module>
    main(args.board_name, board_xml, args)
  File "board_inspector.py", line 29, in main
    native_check()
  File "board_inspector.py", line 22, in native_check
    leaf_1 = parse_cpuid(1, 0, cpu_id)
  File "/home/gvancuts/work/acrn-hypervisor/misc/config_tools/board_inspector/cpuparser/__init__.py", line 36, in parse_cpuid
    return dispatch_table[leaf].read(cpu_id, subleaf)
  File "/home/gvancuts/work/acrn-hypervisor/misc/config_tools/board_inspector/cpuparser/platformbase.py", line 45, in read
    r = cls(cpuid(cpu_id, cls.leaf, subleaf))
  File "/home/gvancuts/work/acrn-hypervisor/misc/config_tools/board_inspector/cpuparser/platformbase.py", line 27, in cpuid
    result = subprocess.run(["cpuid", "-l", str(leaf), "-s", str(subleaf), "-r"], stdout=subprocess.PIPE, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cpuid'
```

For other utilities such as `rdmsr`, things are caught properly and an error message is displayed, e.g.: 
```
$ sudo python3 board_inspector.py ma
'rdmsr' not found, please install it!
Command '['/usr/bin/python3', '/home/gvancuts/work/acrn-hypervisor/misc/config_tools/board_inspector/legacy/board_parser.py', 'ma', '--out', 'ma.xml']' returned non-zero exit status 1.
```

The reason things crash for `cpuid` is because that tool is used **before** the check is done in the code. That check for dependencies is actually done in the `legacy/board_parser.py` file. But the `native_check()` function that is called before it also expects the `cpuid` tool to be installed.

The solution would be to move the dependency check in the main `board_inspector.py` file, **before** the `native_check()` is performed.

**Comment by gvancuts** [comment]
Patch was merged, closing.
