### ISSUE TITLE
[acrn-configuration-tool] Acrn build failed by same module name conflict

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#7001]
**Describe the bug**
If the user installed the lib python package in the host machine, it will fail to build acrn hypervisor since the same package named lib is also used in acrn config tool (static_allocators/lib)

**HV branch**
master

**Steps**
1. root@rbtest:~/acrn-work/acrn-hypervisor#make clean && make BOARD=misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml SCENARIO=misc/config_tools/data/nuc11tnbi5/shared.xml

**Actual result:**
Makefile error occur:

make[1]: Entering directory '/root/acrn-work/acrn-hypervisor/hypervisor'
Board XML is fetched from /root/acrn-work/acrn-hypervisor/misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
Scneario XML is configuration fetched from /root/acrn-work/acrn-hypervisor/misc/config_tools/data/nuc11tnbi5/shared.xml
Traceback (most recent call last):
File "/root/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/main.py", line 41, in <module>
main(args)
File "/root/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/main.py", line 30, in main
module = import_module(f"{module_name}")
File "/usr/lib/python3.8/importlib/_init_.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 848, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/root/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/intx.py", line 10, in <module>
import common, board_cfg_lib, lib.error, lib.lib
File "/usr/lib/python3/dist-packages/lib/_init_.py", line 1, in <module>
abc
NameError: name 'abc' is not defined
make[1]: *** No rule to make target '/root/acrn-work/acrn-hypervisor/build/hypervisor/configs/allocation.xml', needed by '/root/acrn-work/acrn-hypervisor/build/hypervisor/configs/unified.xml'. Stop.
make[1]: Leaving directory '/root/acrn-work/acrn-hypervisor/hypervisor'
make: *** [Makefile:116: hvdefconfig] Error 2

**Expected result**
No Error occurs

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-7566
