### ISSUE TITLE
config_tools: board_inspector cannot generate compliable xml for Qemu

### ISSUE THREAD

**Issue by junjiemao1** [projectacrn/acrn-hypervisor#7058]
Platform: qemu
Board XML is fetched from /root/qemu.xml
Scneario XML is configuration fetched from /git/acrn-hypervisor_myGitRepo/misc/config_tools/data/qemu/shared.xml
Traceback (most recent call last):
File "/git/acrn-hypervisor_myGitRepo/misc/config_tools/static_allocators/main.py", line 41, in <module>
main(args)
File "/git/acrn-hypervisor_myGitRepo/misc/config_tools/static_allocators/main.py", line 31, in main
module.fn(board_etree, scenario_etree, allocation_etree)
File "/git/acrn-hypervisor_myGitRepo/misc/config_tools/static_allocators/intx.py", line 226, in fn
alloc_device_irqs(board_etree, scenario_etree, allocation_etree)
File "/git/acrn-hypervisor_myGitRepo/misc/config_tools/static_allocators/intx.py", line 179, in alloc_device_irqs
for irq in get_irqs_of_device(device_node):
File "/git/acrn-hypervisor_myGitRepo/misc/config_tools/static_allocators/intx.py", line 109, in get_irqs_of_device
irqs.add(int(irq))
ValueError: invalid literal for int() with base 10: '
_SB_.GSIA'
make[1]: *** No rule to make target '/git/acrn-hypervisor_myGitRepo/build/hypervisor/configs/allocation.xml', needed by '/git/acrn-hypervisor_myGitRepo/build/hypervisor/configs/unified.xml'. Stop.
make[1]: Leaving directory '/git/acrn-hypervisor_myGitRepo/hypervisor'
make: *** [Makefile:116: hvdefconfig] Error 2

**Comment by junjiemao1** [comment]
[External_System_ID] ACRN-7595
