### ISSUE TITLE
[acrn-configuration-tool] Share memory should never support 512M since the HV_RAM_SIZE_MAX is limited to 0x40000000 but not a platform specific problem

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#7136]
**Platform**
ADL/TGL/EHL/WHL

**Describe the bug**
steps:
1. Enable share memory and set the value as 512M.
` <IVSHMEM>`
`-            <IVSHMEM_ENABLED>n</IVSHMEM_ENABLED>`
`-            <IVSHMEM_REGION/>`
`+            <IVSHMEM_ENABLED>y</IVSHMEM_ENABLED>`
`+           <IVSHMEM_REGION>hv:/sh,512,0:1</IVSHMEM_REGION>`
`         </IVSHMEM>`

2. build hypervisor and getting error below.
`make[1]: Entering directory '/home/robot/workspace/adl_test_robot/acrn-hypervisor/hypervisor'
Board XML is fetched from /home/robot/workspace/adl_test_robot/acrn-hypervisor/misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
Scneario XML is configuration fetched from /home/robot/workspace/adl_test_robot/acrn-hypervisor/misc/config_tools/data/whl-ipc-i5/industry.xml
Warning: All available pio bases are used by native fully. '0x2F8' is taken by sos legacy vuart 1.
Traceback (most recent call last):
  File "/home/robot/workspace/adl_test_robot/acrn-hypervisor/misc/config_tools/static_allocators/main.py", line 41, in <module>
    main(args)
  File "/home/robot/workspace/adl_test_robot/acrn-hypervisor/misc/config_tools/static_allocators/main.py", line 31, in main
    module.fn(board_etree, scenario_etree, allocation_etree)
  File "/home/robot/workspace/adl_test_robot/acrn-hypervisor/misc/config_tools/static_allocators/hv_ram.py", line 44, in fn
    assert(hv_ram_size <= HV_RAM_SIZE_MAX)
AssertionError
make[1]: *** No rule to make target '/home/robot/workspace/adl_test_robot/acrn-hypervisor/build/hypervisor/configs/allocation.xml', needed by '/home/robot/workspace/adl_test_robot/acrn-hypervisor/build/hypervisor/configs/unified.xml'.  Stop.
make[1]: Leaving directory '/home/robot/workspace/adl_test_robot/acrn-hypervisor/hypervisor'
make: *** [Makefile:111: hvdefconfig] Error 2`

**Expected result**
According the feature description, share memory should be support up to 512M.

**Actual result**
Never support 512M share memory.

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-7388
