### ISSUE TITLE
Segment fault is triggered in course of Virtio-gpu rebooting test

### ISSUE THREAD

**Issue by yakuizhao** [projectacrn/acrn-hypervisor#7296]
In course of vm rebooting with virtio-gpu, it will trigger the segment fault under some scenario.
Thread 123 "mevent" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd37fe640 (LWP 2106)]
0x00007fffd06a45cf in unsafe_free (info=0x7fffc14ba650) at ../src/util/ralloc.c:294
294           info->child = temp->next;
(gdb) bt
#0  0x00007fffd06a45cf in unsafe_free (info=0x7fffc14ba650) at ../src/util/ralloc.c:294
#1  0x00007fffd06a4be3 in unsafe_free (info=<optimized out>) at ../src/util/ralloc.c:295
#2  ralloc_free (ptr=0x7fffc0125d20) at ../src/util/ralloc.c:265
#3  0x00007fffd0c64838 in glsl_type::~glsl_type (this=0x7fffc0125cb0, __in_chrg=<optimized out>) at ../src/compiler/glsl_types.cpp:214
#4  hash_free_type_function (entry=<optimized out>) at ../src/compiler/glsl_types.cpp:516
#5  0x00007fffd06a1b70 in _mesa_hash_table_destroy (ht=0x7fffc0030760,
    delete_function=delete_function@

**Comment by yakuizhao** [comment]
[External_System_ID] ACRN-8745

**Comment by yakuizhao** [comment]
The issue will be closed as the PR is already merged.
