### ISSUE TITLE
[config_tool] Get errors running board_inspector

### ISSUE THREAD

**Issue by zhangqiang4** [projectacrn/acrn-hypervisor#7365]
**Describe the bug**
board_inspector crashed when parsing CPU brand string if CPUID values contain non-viewable characters

root@acrn:/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/board_inspector# python3 board_inspector.py adlp
Traceback (most recent call last):
  File "board_inspector.py", line 140, in <module>
    main(args.board_name, board_xml, args)
  File "board_inspector.py", line 113, in main
    module.extract(args, board_etree)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/board_inspector/extractors/10-processors.py", line 123, in extract
    extract_topology(processors_node)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/board_inspector/extractors/10-processors.py", line 110, in extract_topology
    extract_model(processors_node, cpu_id, family_id, model_id, core_type, native_model_id)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/board_inspector/extractors/10-processors.py", line 46, in extract_model
    n.set("description", brandstring.decode())
  File "src/lxml/etree.pyx", line 831, in lxml.etree._Element.set
  File "src/lxml/apihelpers.pxi", line 593, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
root@acrn:/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/board_inspector# git log --oneline | head -1
cfcea6497 config_tools: add schema of checker schemas

**Comment by zhangqiang4** [comment]
[External_System_ID] ACRN-8683
