### ISSUE TITLE
Build fail on X12DPi-NT6 with v3.0

### ISSUE THREAD

**Issue by fuzhongl** [projectacrn/acrn-hypervisor#7882]
**Describe the bug**
Started with the getting started guide for version 3.0. 
When starting the first build of the hypervisor  get the build
[XML of board and scenario.zip](https://github.com/projectacrn/acrn-hypervisor/files/9070459/XML.of.board.and.scenario.zip)
 error:

**Platform**
Xeon

**Codebase**
v3.0

**Scenario**
Shared

**To Reproduce**
acrn@acrn-virtual-machine:~/acrn-work/acrn-hypervisor$ make BOARD=~/acrn-work/MyConfiguration/X12DPi-N-T-6.board.xml  SCENARIO=~/acrn-work/MyConfiguration/scenario.xml
make[1]: Entering directory '/home/acrn/acrn-work/acrn-hypervisor/hypervisor'
Traceback (most recent call last):
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/main.py", line 41, in <module>
    main(args)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/main.py", line 31, in main
    module.fn(board_etree, scenario_etree, allocation_etree)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/clos.py", line 82, in fn
    create_mask_list_node(board_etree, scenario_etree, allocation_etree, policy_list)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/clos.py", line 53, in create_mask_list_node
    length = common.get_node(f"//cache[@level='3']/capability/capacity_mask_length/text()", board_etree)
  File "/home/acrn/acrn-work/acrn-hypervisor/misc/config_tools/static_allocators/../library/common.py", line 200, in get_node
    assert len(result) <= 1, f"Internal error: multiple element nodes are found for {xpath}"
AssertionError: Internal error: multiple element nodes are found for //cache[@level='3']/capability/capacity_mask_length/text()
make[1]: *** No rule to make target '/home/acrn/acrn-work/acrn-hypervisor/build/hypervisor/configs/allocation.xml', needed by '/home/acrn/acrn-work/acrn-hypervisor/build/hypervisor/configs/unified.xml'.  Stop.
make[1]: Leaving directory '/home/acrn/acrn-work/acrn-hypervisor/hypervisor'
make: *** [Makefile:137: hvdefconfig] Error 2

**Comment by fuzhongl** [comment]
Comments from Junjie:
Welcome to ACRN!

What this calltrace complains about is that the platform has multiple sockets and thus L3 caches which is a case beyond ACRN's common uses today. However, multiple sockets may not hurt if CAT (Cache Allocation
Technology) is not to be enabled which is the case according to your scenario definition.

Here's a one-liner patch to skip the L3 cache related logic at the configuration phase (just cherry-pick the first commit in this branch):

    https://github.com/junjiemao1/acrn-hypervisor/commits/release_3.0

While that allows you to build the hypervisor, there could be other issues when deploying ACRN on a server like yours.

May we know your intended use case for running ACRN on a server?

--
Best Regards
Junjie Mao

**Comment by fuzhongl** [comment]
> Comments from Junjie: Welcome to ACRN!
> 
> What this calltrace complains about is that the platform has multiple sockets and thus L3 caches which is a case beyond ACRN's common uses today. However, multiple sockets may not hurt if CAT (Cache Allocation Technology) is not to be enabled which is the case according to your scenario definition.
> 
> Here's a one-liner patch to skip the L3 cache related logic at the configuration phase (just cherry-pick the first commit in this branch):
> 
> ```
> https://github.com/junjiemao1/acrn-hypervisor/commits/release_3.0
> ```
> 
> While that allows you to build the hypervisor, there could be other issues when deploying ACRN on a server like yours.
> 
> May we know your intended use case for running ACRN on a server?
> 
> -- Best Regards Junjie Mao

Feedback from Jan:
Hi Junjie!

Thanks for the explanation. We are investigating if can use ACRN as hypervisor for an edge cloud in the manufacturing environment. 
We want to deploy real time and non real time VMs for control and regulation of manufacturing the processes.

I was able to build the hypervisor with you fix. So thanks again for that. I will continue with my test and let you know, whether I find any other issues. 

Regards,
Jan
