### ISSUE TITLE
Fail to generate board xml because of non-ascii characters

### ISSUE THREAD

**Issue by Kunhui-Li** [projectacrn/acrn-hypervisor#8388]
**Describe the bug**
Fail to generate board XML file because of non-ascii characters in iomem information.

**To Reproduce**
1. checkout release_3.2 branch.
2. run the command "sudo python3 board_inspector.py my_board", the below error will be found.
```Generating board XML rpl-p. This may take a few minutes...
0%| | 0/100 [00:00<?, ?it/s]2022-06-29 03:08:10-root-WARNING:-Failed to invoke update-pciids: Command '/usr/sbin/update-pciids -q' timed out after 40 seconds. No functional impact is foreseen, but descriptions of PCI devices may be unavailable.
10%|████████████ | 10/100 [00:40<06:00, 4.00s/it]Traceback (most recent call last):
File "/home/acrn/acrn-hypervisor/misc/config_tools/board_inspector/legacy/board_parser.py", line 116, in <module>
misc.generate_info(BOARD_INFO)
File "/home/acrn/acrn-hypervisor/misc/config_tools/board_inspector/legacy/misc.py", line 257, in generate_info
dump_system_ram(config)
File "/home/acrn/acrn-hypervisor/misc/config_tools/board_inspector/legacy/misc.py", line 171, in dump_system_ram
line = mem_info.readline().strip('\n')
File "/usr/lib/python3.10/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 77: invalid start byte
2022-06-29 03:09:30-root-CRITICAL:-Command '['/usr/bin/python3', '/home/acrn/acrn-hypervisor/misc/config_tools/board_inspector/legacy/board_parser.py', 'rpl-p', '--out', 'rpl-p.xml']' returned non-zero exit status 1.
```

**Expected behavior**
Generate the board XML file successfully.

**Comment by Kunhui-Li** [comment]
[External_System_ID] ACRN-9892
